In [1]:
import sys, os
sys.path.append('..')

In [2]:
from src.slices_pipeline.encoder import *
from src.slices_pipeline.loader import *

In [3]:
import pandas as pd
import re

## Count for MP20

In [6]:
def read_results(file):
    rows = []
    pattern = r'^(?P<status>E|x)?\s*(?P<idx>\d+):\s*(?P<material>[a-zA-Z]+-\d+)\s*---\s*(?P<time>[\d\.eE+-]+)'

    for line in open(file).read().strip().split('\n'):
        m = re.match(pattern, line)
        if m:
            rows.append({
                'status': m.group('status') or '',
                'idx': int(m.group('idx')),
                'material_id': m.group('material'),
                'time': float(m.group('time')),
            })

    df = pd.DataFrame(rows)
    return df

In [ ]:
def compile_full_mp20_results():
    mp20_results = read_results("results/results.txt")
    lost = read_results("results/results-lost-true.txt")
    final = pd.concat([lost, mp20_results])
    return final

In [30]:
mp20 = pd.concat([read_split_df("train"), read_split_df("test"), read_split_df("val")])
mp20_results = pd.read_csv("mp20-results.csv").fillna(" ")

# mp20_failed = mp20.merge(mp20_results[mp20_results.status != " "], on="material_id", how="left")
mp20_failed = mp20_results[mp20_results.status != " "].merge(mp20, on="material_id", how="left")
# mp20_failed = mp20_failed[mp20_failed["_merge"] == "left_only"].drop(columns=["_merge", "time"])
mp20_failed

,Unnamed: 0_x,status,material_id,time,Unnamed: 0_y,formation_energy_per_atom,band_gap,pretty_formula,e_above_hull,elements,cif,spacegroup.number
0,0,E,mp-10018,0.123928,30499,0.020409,0.0000,Ac,0.020409,['Ac'],# generated using pymatgen\ndata_Ac\n_symmetry...,225
1,1,E,mp-1211359,5.697293,37174,-2.457178,1.6187,LaMn3Cr4O12,0.041672,"['Cr', 'La', 'Mn', 'O']",# generated using pymatgen\ndata_LaMn3Cr4O12\n...,204
2,7,E,mp-38816,0.633848,34360,-1.634741,0.0000,Mg(TiS2)4,0.031401,"['Mg', 'S', 'Ti']",# generated using pymatgen\ndata_Mg(TiS2)4\n_s...,166
3,9,E,mp-4195,0.241615,5839,-0.665822,0.0000,Tm(NiGe)2,0.000000,"['Tm', 'Ni', 'Ge']",# generated using pymatgen\ndata_Tm(NiGe)2\n_s...,139
4,13,E,mp-1102240,1.459751,42048,-4.167986,6.3522,SrF2,0.064573,"['F', 'Sr']",# generated using pymatgen\ndata_SrF2\n_symmet...,62
...,...,...,...,...,...,...,...,...,...,...,...,...
6768,2131,E,mp-559094,85.720412,36867,-1.066808,0.0685,Cu2H3ClO3,0.041061,"['Cl', 'Cu', 'H', 'O']",# generated using pymatgen\ndata_Cu2H3ClO3\n_s...,11
6769,2239,E,mp-559415,87.655424,36868,-2.565916,0.2441,Na2Cu2Si4O11,0.039796,"['Cu', 'Na', 'O', 'Si']",# generated using pymatgen\ndata_Na2Cu2Si4O11\...,2
6770,2230,E,mp-1223305,89.773011,27221,-1.767493,4.7696,KZnH5(SO5)2,0.011877,"['H', 'K', 'O', 'S', 'Zn']",# generated using pymatgen\ndata_KZnH5(SO5)2\n...,1
6771,1777,E,mp-6036,90.108153,33373,-1.471618,0.0000,CaCu3(RuO3)4,0.027269,"['Ca', 'Cu', 'O', 'Ru']",# generated using pymatgen\ndata_CaCu3(RuO3)4\...,204
6772,22381,E,mp-1183057,94.462643,28583,0.015586,0.0000,Ac,0.015586,['Ac'],# generated using pymatgen\ndata_Ac\n_symmetry...,152

In [31]:
mp20_failed.drop(columns=["Unnamed: 0_y", "Unnamed: 0_x"], inplace=True)

In [32]:
mp20_failed

,status,material_id,time,formation_energy_per_atom,band_gap,pretty_formula,e_above_hull,elements,cif,spacegroup.number
0,E,mp-10018,0.123928,0.020409,0.0000,Ac,0.020409,['Ac'],# generated using pymatgen\ndata_Ac\n_symmetry...,225
1,E,mp-1211359,5.697293,-2.457178,1.6187,LaMn3Cr4O12,0.041672,"['Cr', 'La', 'Mn', 'O']",# generated using pymatgen\ndata_LaMn3Cr4O12\n...,204
2,E,mp-38816,0.633848,-1.634741,0.0000,Mg(TiS2)4,0.031401,"['Mg', 'S', 'Ti']",# generated using pymatgen\ndata_Mg(TiS2)4\n_s...,166
3,E,mp-4195,0.241615,-0.665822,0.0000,Tm(NiGe)2,0.000000,"['Tm', 'Ni', 'Ge']",# generated using pymatgen\ndata_Tm(NiGe)2\n_s...,139
4,E,mp-1102240,1.459751,-4.167986,6.3522,SrF2,0.064573,"['F', 'Sr']",# generated using pymatgen\ndata_SrF2\n_symmet...,62
...,...,...,...,...,...,...,...,...,...,...
6768,E,mp-559094,85.720412,-1.066808,0.0685,Cu2H3ClO3,0.041061,"['Cl', 'Cu', 'H', 'O']",# generated using pymatgen\ndata_Cu2H3ClO3\n_s...,11
6769,E,mp-559415,87.655424,-2.565916,0.2441,Na2Cu2Si4O11,0.039796,"['Cu', 'Na', 'O', 'Si']",# generated using pymatgen\ndata_Na2Cu2Si4O11\...,2
6770,E,mp-1223305,89.773011,-1.767493,4.7696,KZnH5(SO5)2,0.011877,"['H', 'K', 'O', 'S', 'Zn']",# generated using pymatgen\ndata_KZnH5(SO5)2\n...,1
6771,E,mp-6036,90.108153,-1.471618,0.0000,CaCu3(RuO3)4,0.027269,"['Ca', 'Cu', 'O', 'Ru']",# generated using pymatgen\ndata_CaCu3(RuO3)4\...,204
6772,E,mp-1183057,94.462643,0.015586,0.0000,Ac,0.015586,['Ac'],# generated using pymatgen\ndata_Ac\n_symmetry...,152

In [33]:
mp20_failed.to_csv("mp20_failed.csv")

## Теперь sAlex

In [4]:
# salex = pd.read_csv("salex-slices.csv", header=None, delimiter=";", names=["material_id", "slices", "natoms", "e_per_atom"])
slices = pd.read_csv("salex-slices.csv", delimiter=";", names=["orig_id", "slices", "natoms", "e_per_atom"], header=None)
slices = slices[~slices.isna().any(axis=1)]
slices = slices[(slices.natoms < 20) & (slices.e_per_atom < -0.5)]
slices = slices.drop_duplicates(subset=['orig_id'], keep='first')
salex = slices
salex_all = pd.read_csv("save-idx-salex-slices.csv", header=None, names=["orig_id"])

In [5]:
salex

,orig_id,slices,natoms,e_per_atom
4400,6401,Mo Mo Mo Mo Mo Mo W W W W 0 3 - o o 0 3 o o o ...,10.0,-11.283366
4401,662726,Li Li Li Tl Tl Tl Zn Br Br Br Br Br Br Br Br 0...,15.0,-2.911757
4402,1311007,K Sc Pb Pb Cl Cl Cl Cl Cl Cl Cl Cl 0 10 - - o ...,12.0,-4.063211
4403,2604877,Er Er Er Er Er Er Al Al Tc 0 8 o o o 0 3 - o o...,9.0,-5.032145
4404,1634238,Rb Rb Rb Rb Be Be As As S S S S S S S S 0 6 o ...,16.0,-4.106925
...,...,...,...,...
451698,7528197,Ni Ca Ca Cu 0 2 o o o 0 2 o + o 0 2 + o o 0 2 ...,4.0,-3.497263
451699,6471440,Pb Hf Hf Se 0 1 o o o 0 1 + o o 0 1 o + o 0 2 ...,4.0,-7.105467
451700,6261193,F F F F Rb Rb V 0 6 o o + 0 4 o o o 0 5 o o o ...,7.0,-5.105946
451701,1323248,Sr Sr Sr Zn Zn In Au Au Au Au Au Au 0 11 - o o...,12.0,-2.936802
451702,6685301,Na Na Br Ag 0 3 - - o 0 3 - o o 0 3 o - o 0 3 ...,4.0,-2.429143

In [6]:
salex_failed = salex_all.merge(salex, on='orig_id', how='left', indicator=True)
salex_failed = salex_failed[salex_failed['_merge'] == 'left_only'].drop(columns=['_merge', "slices", "natoms", "e_per_atom"])
salex_failed

         orig_id
0              0
1        3917910
2        3917911
3        3917912
4        3917913
...          ...
1267515  7752948
1267516  6685316
1267517  6897796
1267518  6471453
1267519  6261206

[820217 rows x 1 columns]

In [7]:
salex_all

         orig_id
0              0
1        3917910
2        3917911
3        3917912
4        3917913
...          ...
1267515  7752948
1267516  6685316
1267517  6897796
1267518  6471453
1267519  6261206

[1267520 rows x 1 columns]

In [11]:
# !pip install fairchem-core

Collecting fairchem-core
  Downloading fairchem_core-2.2.0-py3-none-any.whl (284 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 284.9/284.9 KB 3.9 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: numba>=0.61.2 in /usr/local/lib/python3.10/dist-packages (from fairchem-core) (0.61.2)
Requirement already satisfied: pymatgen>=2023.10.3 in /usr/local/lib/python3.10/dist-packages (from fairchem-core) (2023.11.12)
Collecting wandb
  Downloading wandb-0.20.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (23.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.2/23.2 MB 51.0 MB/s eta 0:00:0000:0100:01
Collecting ase>=3.25.0
  Downloading ase-3.25.0-py3-none-any.whl (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 70.4 MB/s eta 0:00:00:00:01
Requirement already satisfied: huggingface-hub>=0.27.1 in /usr/local/lib/python3.10/dist-packages (from fairchem-core) (0.32.4)
Collecting lmdb
  Downloading lmdb-1.6.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (294 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.8/294.8 KB 30.0 MB/s eta 0:00:00
Collecting numpy<2.3,>=2.0
  Downloading numpy-2.2.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 51.7 MB/s eta 0:00:0000:0100:01
Collecting e3nn>=0.5
  Downloading e3nn-0.5.6-py3-none-any.whl (448 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 448.0/448.0 KB 1.8 MB/s eta 0:00:0000:01
Collecting orjson
  Downloading orjson-3.10.18-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (132 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.8/132.8 KB 18.6 MB/s eta 0:00:00
Collecting torchtnt
  Downloading torchtnt-0.2.4-py3-none-any.whl (163 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.5/163.5 KB 22.4 MB/s eta 0:00:00
Collecting torch~=2.6.0
  Downloading torch-2.6.0-cp310-cp310-manylinux1_x86_64.whl (766.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 766.7/766.7 MB 1.3 MB/s eta 0:00:0000:0100:01
Collecting ase-db-backends>=0.10.0
  Downloading ase_db_backends-0.10.0-py3-none-any.whl (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.9/42.9 KB 6.5 MB/s eta 0:00:00
Collecting submitit
  Downloading submitit-1.5.3-py3-none-any.whl (75 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.5/75.5 KB 11.2 MB/s eta 0:00:00
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from fairchem-core) (4.67.1)
Collecting hydra-core
  Downloading hydra_core-1.3.2-py3-none-any.whl (154 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.5/154.5 KB 20.7 MB/s eta 0:00:00
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from fairchem-core) (5.4.1)
Requirement already satisfied: tensorboard in /usr/local/lib/python3.10/dist-packages (from fairchem-core) (2.15.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from fairchem-core) (2.32.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from ase>=3.25.0->fairchem-core) (1.13.0)
Requirement already satisfied: matplotlib>=3.3.4 in /usr/local/lib/python3.10/dist-packages (from ase>=3.25.0->fairchem-core) (3.10.3)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 72.9 MB/s eta 0:00:00:00:01
Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 KB 6.1 MB/s eta 0:00:00
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from ase-db-backends>=0.10.0->fairchem-core) (3.4.8)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from e3nn>=0.5->fairchem-core) (1.13.3)
Collecting opt_einsum_fx>=0.1.4
  Downloading opt_einsum_fx-0.1.4-py3-none-any.whl (13 kB)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.27.1->fairchem-core) (2024.6.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.27.1->fairchem-core) (4.12.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.27.1->fairchem-core) (25.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.27.1->fairchem-core) (1.1.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.27.1->fairchem-core) (3.13.1)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /usr/local/lib/python3.10/dist-packages (from numba>=0.61.2->fairchem-core) (0.44.0)
Requirement already satisfied: plotly>=4.5.0 in /usr/local/lib/python3.10/dist-packages (from pymatgen>=2023.10.3->fairchem-core) (6.1.1)
Requirement already satisfied: monty>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from pymatgen>=2023.10.3->fairchem-core) (2025.3.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from pymatgen>=2023.10.3->fairchem-core) (2.2.3)
Requirement already satisfied: networkx>=2.2 in /usr/local/lib/python3.10/dist-packages (from pymatgen>=2023.10.3->fairchem-core) (3.3)
Requirement already satisfied: ruamel.yaml>=0.17.0 in /usr/local/lib/python3.10/dist-packages (from pymatgen>=2023.10.3->fairchem-core) (0.18.11)
Requirement already satisfied: uncertainties>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from pymatgen>=2023.10.3->fairchem-core) (3.2.3)
Requirement already satisfied: palettable>=3.1.1 in /usr/local/lib/python3.10/dist-packages (from pymatgen>=2023.10.3->fairchem-core) (3.3.3)
Requirement already satisfied: tabulate in /usr/local/lib/python3.10/dist-packages (from pymatgen>=2023.10.3->fairchem-core) (0.9.0)
Requirement already satisfied: pybtex in /usr/local/lib/python3.10/dist-packages (from pymatgen>=2023.10.3->fairchem-core) (0.24.0)
Requirement already satisfied: spglib>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from pymatgen>=2023.10.3->fairchem-core) (2.6.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from pymatgen>=2023.10.3->fairchem-core) (1.5.1)
Collecting nvidia-cublas-cu12==12.4.5.8
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.1 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cusparselt-cu12==0.6.2
  Downloading nvidia_cusparselt_cu12-0.6.2-py3-none-manylinux2014_x86_64.whl (150.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.1/150.1 MB 6.0 MB/s eta 0:00:0000:0100:01
Collecting nvidia-nccl-cu12==2.21.5
  Downloading nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl (188.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.7/188.7 MB 6.1 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch~=2.6.0->fairchem-core) (3.1.4)
Collecting nvidia-cudnn-cu12==9.1.0.70
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.7 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cusolver-cu12==11.6.1.9
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 8.7 MB/s eta 0:00:0000:0100:01
Collecting nvidia-nvjitlink-cu12==12.4.127
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 65.3 MB/s eta 0:00:0000:0100:01
Collecting nvidia-curand-cu12==10.3.5.147
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 20.3 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cuda-runtime-cu12==12.4.127
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 KB 53.9 MB/s eta 0:00:00
Collecting nvidia-cuda-cupti-cu12==12.4.127
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 80.8 MB/s eta 0:00:0000:0100:01
Collecting sympy
  Downloading sympy-1.13.1-py3-none-any.whl (6.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 85.1 MB/s eta 0:00:00:00:0100:01
Collecting triton==3.2.0
  Downloading triton-3.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (253.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.1/253.1 MB 4.2 MB/s eta 0:00:0000:0100:01
Collecting nvidia-nvtx-cu12==12.4.127
  Downloading nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 KB 11.3 MB/s eta 0:00:00
Collecting nvidia-cufft-cu12==11.2.1.3
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 3.6 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cusparse-cu12==12.3.1.170
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 3.6 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cuda-nvrtc-cu12==12.4.127
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 17.1 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->e3nn>=0.5->fairchem-core) (1.3.0)
Collecting antlr4-python3-runtime==4.9.*
  Using cached antlr4_python3_runtime-4.9.3-py3-none-any.whl
Collecting omegaconf<2.4,>=2.2
  Downloading omegaconf-2.3.0-py3-none-any.whl (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 KB 11.9 MB/s eta 0:00:00
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->fairchem-core) (3.10)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->fairchem-core) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->fairchem-core) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->fairchem-core) (2025.4.26)
Collecting cloudpickle>=1.2.1
  Downloading cloudpickle-3.1.1-py3-none-any.whl (20 kB)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard->fairchem-core) (3.8)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard->fairchem-core) (3.1.3)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.10/dist-packages (from tensorboard->fairchem-core) (2.2.2)
Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in /usr/local/lib/python3.10/dist-packages (from tensorboard->fairchem-core) (1.2.2)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard->fairchem-core) (70.2.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard->fairchem-core) (0.7.2)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in /usr/local/lib/python3.10/dist-packages (from tensorboard->fairchem-core) (4.25.7)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard->fairchem-core) (2.40.2)
Requirement already satisfied: six>1.9 in /usr/lib/python3/dist-packages (from tensorboard->fairchem-core) (1.16.0)
Requirement already satisfied: grpcio>=1.48.2 in /usr/local/lib/python3.10/dist-packages (from tensorboard->fairchem-core) (1.71.0)
Collecting pyre-extensions
  Downloading pyre_extensions-0.0.32-py3-none-any.whl (12 kB)
Requirement already satisfied: psutil in /root/.local/lib/python3.10/site-packages (from torchtnt->fairchem-core) (7.0.0)
Requirement already satisfied: click!=8.0.0,>=7.1 in /usr/lib/python3/dist-packages (from wandb->fairchem-core) (8.0.3)
Collecting sentry-sdk>=2.0.0
  Downloading sentry_sdk-2.29.1-py2.py3-none-any.whl (341 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.6/341.6 KB 37.2 MB/s eta 0:00:00
Collecting gitpython!=3.1.29,>=1.0.0
  Downloading GitPython-3.1.44-py3-none-any.whl (207 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.6/207.6 KB 25.9 MB/s eta 0:00:00
Requirement already satisfied: platformdirs in /root/.local/lib/python3.10/site-packages (from wandb->fairchem-core) (4.3.8)
Collecting pydantic<3
  Downloading pydantic-2.11.5-py3-none-any.whl (444 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 444.2/444.2 KB 7.8 MB/s eta 0:00:0000:01
Collecting setproctitle
  Downloading setproctitle-1.3.6-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (30 kB)
Collecting gitdb<5,>=4.0.1
  Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 9.5 MB/s eta 0:00:00
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard->fairchem-core) (0.4.2)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard->fairchem-core) (5.5.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard->fairchem-core) (4.9.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<2,>=0.5->tensorboard->fairchem-core) (2.0.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.4->ase>=3.25.0->fairchem-core) (1.4.8)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.4->ase>=3.25.0->fairchem-core) (4.58.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.4->ase>=3.25.0->fairchem-core) (2.9.0.post0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.4->ase>=3.25.0->fairchem-core) (0.12.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.4->ase>=3.25.0->fairchem-core) (11.0.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.4->ase>=3.25.0->fairchem-core) (1.3.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/lib/python3/dist-packages (from matplotlib>=3.3.4->ase>=3.25.0->fairchem-core) (2.4.7)
Requirement already satisfied: opt-einsum in /usr/local/lib/python3.10/dist-packages (from opt_einsum_fx>=0.1.4->e3nn>=0.5->fairchem-core) (3.4.0)
Requirement already satisfied: narwhals>=1.15.1 in /usr/local/lib/python3.10/dist-packages (from plotly>=4.5.0->pymatgen>=2023.10.3->fairchem-core) (1.41.0)
Collecting pydantic-core==2.33.2
  Downloading pydantic_core-2.33.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 10.5 MB/s eta 0:00:00:00:01
Collecting typing-inspection>=0.4.0
  Downloading typing_inspection-0.4.1-py3-none-any.whl (14 kB)
Collecting annotated-types>=0.6.0
  Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in /usr/local/lib/python3.10/dist-packages (from ruamel.yaml>=0.17.0->pymatgen>=2023.10.3->fairchem-core) (0.2.12)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard->fairchem-core) (2.1.5)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->pymatgen>=2023.10.3->fairchem-core) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->pymatgen>=2023.10.3->fairchem-core) (2025.2)
Requirement already satisfied: latexcodec>=1.0.4 in /usr/local/lib/python3.10/dist-packages (from pybtex->pymatgen>=2023.10.3->fairchem-core) (3.0.0)
Collecting typing-inspect
  Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Collecting smmap<6,>=3.0.1
  Downloading smmap-5.0.2-py3-none-any.whl (24 kB)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard->fairchem-core) (0.6.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/lib/python3/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard->fairchem-core) (3.2.0)
Collecting mypy-extensions>=0.3.0
  Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Installing collected packages: triton, nvidia-cusparselt-cu12, lmdb, antlr4-python3-runtime, typing-inspection, sympy, smmap, setproctitle, sentry-sdk, pymysql, pydantic-core, psycopg2-binary, orjson, omegaconf, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, numpy, mypy-extensions, cloudpickle, annotated-types, typing-inspect, submitit, pydantic, nvidia-cusparse-cu12, nvidia-cudnn-cu12, hydra-core, gitdb, pyre-extensions, nvidia-cusolver-cu12, gitpython, wandb, torch, ase, torchtnt, opt_einsum_fx, ase-db-backends, e3nn, fairchem-core
  Attempting uninstall: triton
    Found existing installation: triton 2.2.0
    Uninstalling triton-2.2.0:
      Successfully uninstalled triton-2.2.0
  Attempting uninstall: nvidia-cusparselt-cu12
    Found existing installation: nvidia-cusparselt-cu12 0.6.3
    Uninstalling nvidia-cusparselt-cu12-0.6.3:
      Successfully uninstalled nvidia-cusparselt-cu12-0.6.3
  Attempting uninstall: sympy
    Found existing installation: sympy 1.13.3
    Uninstalling sympy-1.13.3:
      Successfully uninstalled sympy-1.13.3
  Attempting uninstall: nvidia-nvtx-cu12
    Found existing installation: nvidia-nvtx-cu12 12.8.55
    Uninstalling nvidia-nvtx-cu12-12.8.55:
      Successfully uninstalled nvidia-nvtx-cu12-12.8.55
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.8.61
    Uninstalling nvidia-nvjitlink-cu12-12.8.61:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.8.61
  Attempting uninstall: nvidia-nccl-cu12
    Found existing installation: nvidia-nccl-cu12 2.26.2
    Uninstalling nvidia-nccl-cu12-2.26.2:
      Successfully uninstalled nvidia-nccl-cu12-2.26.2
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.9.55
    Uninstalling nvidia-curand-cu12-10.3.9.55:
      Successfully uninstalled nvidia-curand-cu12-10.3.9.55
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.3.3.41
    Uninstalling nvidia-cufft-cu12-11.3.3.41:
      Successfully uninstalled nvidia-cufft-cu12-11.3.3.41
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.8.57
    Uninstalling nvidia-cuda-runtime-cu12-12.8.57:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.8.57
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.8.61
    Uninstalling nvidia-cuda-nvrtc-cu12-12.8.61:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.8.61
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.8.57
    Uninstalling nvidia-cuda-cupti-cu12-12.8.57:

In [13]:
# !pip install "numpy==1.26.4"

Collecting numpy==1.26.4
  Using cached numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.2.6
    Uninstalling numpy-2.2.6:
      Successfully uninstalled numpy-2.2.6
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.17.2+cu118 requires torch==2.2.2, but you have torch 2.6.0 which is incompatible.
slices 2.0.10 requires ase==3.22.1, but you have ase 3.25.0 which is incompatible.
fairchem-core 2.2.0 requires numpy<2.3,>=2.0, but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [8]:
from fairchem.core.datasets import AseDBDataset

In [ ]:
config_kwargs = {}
dataset_paths = [
    "../data/raw/sAlex/train"
]
df = AseDBDataset(config=dict(src=dataset_paths, **config_kwargs))

In [10]:
from tqdm import tqdm

In [11]:
salex_failed

         orig_id
0              0
1        3917910
2        3917911
3        3917912
4        3917913
...          ...
1267515  7752948
1267516  6685316
1267517  6897796
1267518  6471453
1267519  6261206

[820217 rows x 1 columns]

In [19]:
from tqdm import tqdm
import torch

In [20]:
def tensor_to_py(val):
    if isinstance(val, torch.Tensor):
        if val.dim() == 0 or val.numel() == 1:
            return val.item()
        else:
            return val.tolist()
    return val

data = [
    {attr: tensor_to_py(val) for attr, val in df[orig_id]}
    for orig_id in tqdm(salex_failed['orig_id'], total=salex_failed.shape[0])
]
salex_failed_df = pd.DataFrame(data)

100%|██████████| 820217/820217 [17:27<00:00, 782.83it/s]

In [31]:
def check_types(dataset):
    return dataset.apply(type).value_counts()

In [50]:
check_types(salex_failed_df.tags)

tags
<class 'list'>    820192
<class 'int'>         25
Name: count, dtype: int64

In [21]:
salex_failed_df

,atomic_numbers,batch,cell,cell_offsets,charge,edge_index,energy,fixed,forces,natoms,nedges,pbc,pos,sid,spin,stress,tags
0,"[47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 4...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[[[5.087919235229492, 0.2699517011642456, 0.00...",[],0,"[[], []]",-38.892906,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[[0.000762699986808002, 0.0013637800002470613,...",15,0,"[[True, True, True]]","[[2.40321946144104, 0.7705909013748169, 7.3934...",[agm003285455_0_0],0,"[[[-0.00012834678636863828, 0.0001186694789794...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"
1,"[61, 61, 61, 61, 39, 39, 30, 30, 30, 30]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[[[3.6860270500183105, 0.0, -0.493714004755020...",[],0,"[[], []]",-39.487530,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[[-0.024534450843930244, -0.0, -0.225044593214...",10,0,"[[True, True, True]]","[[0.16755662858486176, 3.9168171882629395, 1.2...",[agm005855838_2_22],0,"[[[0.0018122814362868667, -0.0, -0.00052818120...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"
2,"[20, 20, 20, 20, 83, 83, 83, 83, 83, 83]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[[[5.881773471832275, 0.20262520015239716, 0.0...",[],0,"[[], []]",-36.063663,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[[7.44400022085756e-05, -0.0016903900541365147...",10,0,"[[True, True, True]]","[[4.499755382537842, 1.054145097732544, 6.7248...",[agm005530395_0_0],0,"[[[2.58729651250178e-05, 6.529485108330846e-05...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"
3,"[20, 20, 20, 20, 83, 83, 83, 83, 83, 83]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[[[5.974905967712402, 0.1534552127122879, 0.0]...",[],0,"[[], []]",-35.949062,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[[0.009413749910891056, -0.0046580699272453785...",10,0,"[[True, True, True]]","[[4.634240627288818, 0.9793316721916199, 6.217...",[agm005530395_2_28],0,"[[[0.0010809592204168439, -0.00193619320634752...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"
4,"[20, 20, 20, 20, 83, 83, 83, 83, 83, 83]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[[[5.8633928298950195, 0.26234400272369385, 0....",[],0,"[[], []]",-35.844959,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[[0.08243271708488464, -0.047273918986320496, ...",10,0,"[[True, True, True]]","[[4.548398971557617, 1.0716904401779175, 6.105...",[agm005530395_2_33],0,"[[[-0.006946321576833725, 0.003650974482297897...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820212,"[75, 45, 38, 38]","[0, 0, 0, 0]","[[[4.749109268188477, 0.0, -0.0], [0.0, 4.7459...",[],0,"[[], []]",-19.553513,"[0, 0, 0, 0]","[[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, ...",4,0,"[[True, True, True]]","[[2.3745546340942383, 0.0, 2.154287099838257],...",[agm004080187_0_0],0,"[[[0.00013495550956577063, -0.0, -0.0], [-0.0,...","[1, 1, 1, 1]"
820213,"[12, 49, 49, 83]","[0, 0, 0, 0]","[[[4.719408988952637, 0.0, 0.0], [2.3597044944...",[],0,"[[], []]",-10.750687,"[0, 0, 0, 0]","[[0.0, 0.0, -0.0072018299251794815], [-0.0, -0...",4,0,"[[True, True, True]]","[[7.079111099243164, 4.087126731872559, 6.1481...",[agm005124545_2_35],0,"[[[-0.0004515302134677768, -0.0, 0.0], [-0.0, ...","[1, 1, 1, 1]"
820214,"[91, 79, 83, 62]","[0, 0, 0, 0]","[[[5.3536906242370605, 0.0, 0.0], [2.676845312...",[],0,"[[], []]",-22.559755,"[0, 0, 0, 0]","[[0.0, 0.0, 0.0], [0.0, -0.0, 0.0], [-0.0, 0.0...",4,0,"[[True, True, True]]","[[8.030535697937012, 4.63643217086792, 3.27845...",[agm001377613_0_0],0,"[[[-4.869763506576419e-05, -0.0, -0.0], [-0.0,...","[1, 1, 1, 1]"
820215,"[3, 3, 3, 3, 3, 3, 31]","[0, 0, 0, 0, 0, 0, 0]","[[[5.984238147735596, 0.0, 0.0], [-1.994746088...",[],0,"[[], []]",-10.909159,"[0, 0, 0, 0, 0, 0, 0]","[[0.0, -0.0, 0.0], [-0.0, -0.0, -0.0], [-0.0, ...",7,0,"[[True, True, True]]","[[-0.9973730444908142, 2.8209969997406006, 2.4...",[agm005405321_0_0],0,"[[[-0.0002065340377157554, -0.0, -0.0], [-0.0,...","[1, 1, 1, 1, 1, 1, 1]"
820216,"[69, 83, 83, 49]","[0, 0, 0, 0]","[[[4.378093719482422, 0.0, -0.0], [2.189046859...",[],0,"[[], []]",-15.744371,"[0, 0, 0, 0]","[[-0.0, 0.0, -0.0], [0.0, 0.0, -0.002182590076...",4,0,"[[True, True, True]]","[[0.0, 0.0, 0.0], [2.189049005508423, 1.263848...",[agm001970532_2_9],0,"[[[-0.0005415566847659647, -0.0, 0.0], [-0.0, ...","[1, 1, 1, 1]"

In [ ]:
print(salex_failed_df['atomic_numbers'].apply(type).value_counts())

atomic_numbers
<class 'list'>    820192
<class 'int'>         25
Name: count, dtype: int64

In [24]:
salex_failed_df_copy = salex_failed_df.copy()

In [51]:
salex_failed_df_copy['atomic_numbers'] = salex_failed_df_copy['atomic_numbers'].apply(lambda x: x if isinstance(x, list) else [x])
salex_failed_df_copy['batch'] = salex_failed_df_copy['batch'].apply(lambda x: x if isinstance(x, list) else [x])
salex_failed_df_copy['fixed'] = salex_failed_df_copy['fixed'].apply(lambda x: x if isinstance(x, list) else [x])
salex_failed_df_copy['tags'] = salex_failed_df_copy['tags'].apply(lambda x: x if isinstance(x, list) else [x])

In [52]:
salex_failed_df_copy['atomic_numbers'].apply(type).value_counts()

atomic_numbers
<class 'list'>    820217
Name: count, dtype: int64

In [53]:
salex_failed_df_copy.to_parquet('salex_failed.parquet')

In [54]:
a = pd.read_parquet('salex_failed.parquet')
a

,atomic_numbers,batch,cell,cell_offsets,charge,edge_index,energy,fixed,forces,natoms,nedges,pbc,pos,sid,spin,stress,tags
0,"[47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 4...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[[[5.087919235229492, 0.2699517011642456, 0.00...",[],0,"[[], []]",-38.892906,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[[0.000762699986808002, 0.0013637800002470613,...",15,0,"[[True, True, True]]","[[2.40321946144104, 0.7705909013748169, 7.3934...",[agm003285455_0_0],0,"[[[-0.00012834678636863828, 0.0001186694789794...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"
1,"[61, 61, 61, 61, 39, 39, 30, 30, 30, 30]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[[[3.6860270500183105, 0.0, -0.493714004755020...",[],0,"[[], []]",-39.487530,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[[-0.024534450843930244, -0.0, -0.225044593214...",10,0,"[[True, True, True]]","[[0.16755662858486176, 3.9168171882629395, 1.2...",[agm005855838_2_22],0,"[[[0.0018122814362868667, -0.0, -0.00052818120...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"
2,"[20, 20, 20, 20, 83, 83, 83, 83, 83, 83]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[[[5.881773471832275, 0.20262520015239716, 0.0...",[],0,"[[], []]",-36.063663,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[[7.44400022085756e-05, -0.0016903900541365147...",10,0,"[[True, True, True]]","[[4.499755382537842, 1.054145097732544, 6.7248...",[agm005530395_0_0],0,"[[[2.58729651250178e-05, 6.529485108330846e-05...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"
3,"[20, 20, 20, 20, 83, 83, 83, 83, 83, 83]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[[[5.974905967712402, 0.1534552127122879, 0.0]...",[],0,"[[], []]",-35.949062,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[[0.009413749910891056, -0.0046580699272453785...",10,0,"[[True, True, True]]","[[4.634240627288818, 0.9793316721916199, 6.217...",[agm005530395_2_28],0,"[[[0.0010809592204168439, -0.00193619320634752...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"
4,"[20, 20, 20, 20, 83, 83, 83, 83, 83, 83]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[[[5.8633928298950195, 0.26234400272369385, 0....",[],0,"[[], []]",-35.844959,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[[0.08243271708488464, -0.047273918986320496, ...",10,0,"[[True, True, True]]","[[4.548398971557617, 1.0716904401779175, 6.105...",[agm005530395_2_33],0,"[[[-0.006946321576833725, 0.003650974482297897...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820212,"[75, 45, 38, 38]","[0, 0, 0, 0]","[[[4.749109268188477, 0.0, -0.0], [0.0, 4.7459...",[],0,"[[], []]",-19.553513,"[0, 0, 0, 0]","[[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, ...",4,0,"[[True, True, True]]","[[2.3745546340942383, 0.0, 2.154287099838257],...",[agm004080187_0_0],0,"[[[0.00013495550956577063, -0.0, -0.0], [-0.0,...","[1, 1, 1, 1]"
820213,"[12, 49, 49, 83]","[0, 0, 0, 0]","[[[4.719408988952637, 0.0, 0.0], [2.3597044944...",[],0,"[[], []]",-10.750687,"[0, 0, 0, 0]","[[0.0, 0.0, -0.0072018299251794815], [-0.0, -0...",4,0,"[[True, True, True]]","[[7.079111099243164, 4.087126731872559, 6.1481...",[agm005124545_2_35],0,"[[[-0.0004515302134677768, -0.0, 0.0], [-0.0, ...","[1, 1, 1, 1]"
820214,"[91, 79, 83, 62]","[0, 0, 0, 0]","[[[5.3536906242370605, 0.0, 0.0], [2.676845312...",[],0,"[[], []]",-22.559755,"[0, 0, 0, 0]","[[0.0, 0.0, 0.0], [0.0, -0.0, 0.0], [-0.0, 0.0...",4,0,"[[True, True, True]]","[[8.030535697937012, 4.63643217086792, 3.27845...",[agm001377613_0_0],0,"[[[-4.869763506576419e-05, -0.0, -0.0], [-0.0,...","[1, 1, 1, 1]"
820215,"[3, 3, 3, 3, 3, 3, 31]","[0, 0, 0, 0, 0, 0, 0]","[[[5.984238147735596, 0.0, 0.0], [-1.994746088...",[],0,"[[], []]",-10.909159,"[0, 0, 0, 0, 0, 0, 0]","[[0.0, -0.0, 0.0], [-0.0, -0.0, -0.0], [-0.0, ...",7,0,"[[True, True, True]]","[[-0.9973730444908142, 2.8209969997406006, 2.4...",[agm005405321_0_0],0,"[[[-0.0002065340377157554, -0.0, -0.0], [-0.0,...","[1, 1, 1, 1, 1, 1, 1]"
820216,"[69, 83, 83, 49]","[0, 0, 0, 0]","[[[4.378093719482422, 0.0, -0.0], [2.189046859...",[],0,"[[], []]",-15.744371,"[0, 0, 0, 0]","[[-0.0, 0.0, -0.0], [0.0, 0.0, -0.002182590076...",4,0,"[[True, True, True]]","[[0.0, 0.0, 0.0], [2.189049005508423, 1.263848...",[agm001970532_2_9],0,"[[[-0.0005415566847659647, -0.0, 0.0], [-0.0, ...","[1, 1, 1, 1]"

In [60]:
a.iloc[0]

atomic_numbers    [47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 4...
batch                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
cell              [[[5.087919235229492, 0.2699517011642456, 0.00...
cell_offsets                                                     []
charge                                                            0
edge_index                                                 [[], []]
energy                                                   -38.892906
fixed                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
forces            [[0.000762699986808002, 0.0013637800002470613,...
natoms                                                           15
nedges                                                            0
pbc                                            [[True, True, True]]
pos               [[2.40321946144104, 0.7705909013748169, 7.3934...
sid                                              [agm003285455_0_0]
spin                                                              0
stress            [[[-0.00012834678636863828, 0.0001186694789794...
tags                  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Name: 0, dtype: object

In [18]:
data = []

for idx in tqdm(salex_failed.orig_id, total=salex_failed.shape[0]):
# for row in tqdm(range(salex_failed.shape[0])):
    failed_row = df[idx]
    result = {}
    result['idx'] = idx
    for attr, val in failed_row:
        result[attr] = val if not isinstance(val, torch.Tensor) else val.item() if val.dim() == 0 or val.numel() == 1 else val.tolist()
    data.append(result)
    # for attr in dir(failed_row):
    #     if attr.startswith('_'):
    #         continue
    #     value = getattr(failed_row, attr)
    #     print(attr, value)
    #     for val in 
    #     result[attr] = value.item() if hasattr(value, 'item') else value
    # data.append(result)

salex_failed_df = pd.DataFrame(data)
salex_failed_df

  2%|▏         | 15617/820217 [00:56<48:14, 277.95it/s]
  0%|          | 2427/820217 [00:03<19:00, 717.21it/s]

KeyboardInterrupt:

In [25]:
df[0]

AtomicData(atomic_numbers=[15], batch=[15], cell=[1, 3, 3], cell_offsets=[0, 3], charge=[1], edge_index=[2, 0], energy=[1], fixed=[15], forces=[15, 3], natoms=[1], nedges=[1], pbc=[1, 3], pos=[15, 3], sid=[1], spin=[1], stress=[1, 3, 3], tags=[15])

In [35]:
df[0].__dir__()

['__keys__',
 'pos',
 'atomic_numbers',
 'cell',
 'pbc',
 'natoms',
 'edge_index',
 'cell_offsets',
 'nedges',
 'charge',
 'spin',
 'fixed',
 'tags',
 'sid',
 'energy',
 'forces',
 'stress',
 'batch',
 '__slices__',
 '__cumsum__',
 '__cat_dims__',
 '__natoms_list__',
 '__module__',
 '__init__',
 'task_name',
 'assign_batch_stats',
 'get_batch_stats',
 'validate',
 'from_ase',
 'to_ase_single',
 'to_ase',
 'from_dict',
 'to_dict',
 'values',
 'num_nodes',
 'num_edges',
 'num_graphs',
 '__len__',
 'get',
 '__getitem__',
 '__setitem__',
 '__setattr__',
 '__delitem__',
 'keys',
 '__contains__',
 '__iter__',
 '__call__',
 '__cat_dim__',
 '__inc__',
 '__apply__',
 'apply',
 'contiguous',
 'to',
 'cpu',
 'cuda',
 'clone',
 '__repr__',
 'get_example',
 'index_select',
 'batch_to_atomicdata_list',
 '__dict__',
 '__weakref__',
 '__doc__',
 '__new__',
 '__hash__',
 '__str__',
 '__getattribute__',
 '__delattr__',
 '__lt__',
 '__le__',
 '__eq__',
 '__ne__',
 '__gt__',
 '__ge__',
 '__reduce_ex__',
 '__reduce__',
 '__subclasshook__',
 '__init_subclass__',
 '__format__',
 '__sizeof__',
 '__dir__',
 '__class__']

In [30]:
for i in df[0]:
    print(i)

('atomic_numbers', tensor([47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 48, 48]))
('batch', tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))
('cell', tensor([[[ 5.0879e+00,  2.6995e-01,  6.9364e-03],
         [-3.0440e-01,  7.2033e+00, -6.6108e-01],
         [-7.8136e-01, -4.2141e+00,  7.8313e+00]]]))
('cell_offsets', tensor([], size=(0, 3)))
('charge', tensor([0]))
('edge_index', tensor([], size=(2, 0), dtype=torch.int64))
('energy', tensor([-38.8929]))
('fixed', tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))
('forces', tensor([[ 7.6270e-04,  1.3638e-03,  1.5042e-03],
        [-7.6270e-04, -1.3638e-03, -1.5042e-03],
        [-0.0000e+00, -0.0000e+00, -0.0000e+00],
        [-3.4816e-04, -9.9190e-05, -1.1666e-03],
        [ 3.4816e-04,  9.9190e-05,  1.1666e-03],
        [ 8.4745e-04, -8.5680e-05, -5.7949e-04],
        [-8.4745e-04,  8.5680e-05,  5.7949e-04],
        [-1.2281e-03, -1.0627e-03, -9.8179e-04],
        [ 1.2281e-03,  1.0627e-03,  9.8179e-04],
        [-2.6494e-04, -1.1562e-04, -5.4013e-04],
        [ 2.6494e-04,  1.1562e-04,  5.4013e-04],
        [-6.3951e-04,  7.3755e-04,  9.0390e-04],
        [ 6.3951e-04, -7.3755e-04, -9.0390e-04],
        [-1.7734e-04, -7.1530e-05, -2.2658e-04],
        [ 1.7734e-04,  7.1530e-05,  2.2658e-04]]))
('natoms', tensor([15]))
('nedges', tensor([0]))
('pbc', tensor([[True, True, True]]))
('pos', tensor([[ 2.4032,  0.7706,  7.3935],
        [ 1.5989,  2.4886, -0.2163],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.8823, -1.9741,  4.6710],
        [ 3.1198,  5.2334,  2.5062],
        [-0.1040,  0.5043,  5.9308],
        [ 4.1062,  2.7549,  1.2464],
        [ 1.5377,  2.7480,  2.7285],
        [ 2.4644,  0.5112,  4.4486],
        [ 1.4867,  3.0003,  5.7132],
        [ 2.5154,  0.2589,  1.4639],
        [ 3.3805, -1.6900,  6.1507],
        [ 0.6217,  4.9492,  1.0265],
        [ 4.0425,  3.0430,  4.2369],
        [-0.0403,  0.2162,  2.9403]]))
('sid', ['agm003285455_0_0'])
('spin', tensor([0]))
('stress', tensor([[[-1.2835e-04,  1.1867e-04, -3.2632e-05],
         [ 1.1867e-04, -2.1911e-04,  1.2592e-04],
         [-3.2632e-05,  1.2592e-04, -5.9592e-06]]]))
('tags', tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [28]:
df[0].forces

tensor([[ 7.6270e-04,  1.3638e-03,  1.5042e-03],
        [-7.6270e-04, -1.3638e-03, -1.5042e-03],
        [-0.0000e+00, -0.0000e+00, -0.0000e+00],
        [-3.4816e-04, -9.9190e-05, -1.1666e-03],
        [ 3.4816e-04,  9.9190e-05,  1.1666e-03],
        [ 8.4745e-04, -8.5680e-05, -5.7949e-04],
        [-8.4745e-04,  8.5680e-05,  5.7949e-04],
        [-1.2281e-03, -1.0627e-03, -9.8179e-04],
        [ 1.2281e-03,  1.0627e-03,  9.8179e-04],
        [-2.6494e-04, -1.1562e-04, -5.4013e-04],
        [ 2.6494e-04,  1.1562e-04,  5.4013e-04],
        [-6.3951e-04,  7.3755e-04,  9.0390e-04],
        [ 6.3951e-04, -7.3755e-04, -9.0390e-04],
        [-1.7734e-04, -7.1530e-05, -2.2658e-04],
        [ 1.7734e-04,  7.1530e-05,  2.2658e-04]])

## Прочее

In [27]:
mp20_failed._merge.unique()

['left_only', 'both']
Categories (3, object): ['left_only', 'right_only', 'both']

In [19]:
a = pd.read_csv("mp20-results.csv")
a

       Unnamed: 0 status material_id        time
0               0      E    mp-10018    0.123928
1               1      E  mp-1211359    5.697293
2               2    NaN  mp-1209679    0.789871
3               3    NaN  mp-1020059    0.620733
4               4    NaN  mp-1189429    1.205847
...           ...    ...         ...         ...
45224        2239      E   mp-559415   87.655424
45225        2230      E  mp-1223305   89.773011
45226        1777      E     mp-6036   90.108153
45227       22381      E  mp-1183057   94.462643
45228         512    NaN  mp-1215784  144.891749

[45229 rows x 4 columns]

In [20]:
a.shape[0], a.nunique()

(45229,
 Unnamed: 0     45208
 status             2
 material_id    45229
 time           45197
 dtype: int64)

In [18]:
mp20.shape[0], mp20.nunique()

(45229,
 Unnamed: 0                   45229
 material_id                  45229
 formation_energy_per_atom    45148
 band_gap                     15585
 pretty_formula               37217
 e_above_hull                 25015
 elements                     26103
 cif                          45229
 spacegroup.number              177
 dtype: int64)

In [ ]:
lost

   status    idx material_id      time
0       E   9420    mp-10018  0.123928
1       E   9421  mp-1211359  5.697293
2           9422  mp-1209679  0.789871
3           9423  mp-1020059  0.620733
4           9424  mp-1189429  1.205847
5           9425   mp-756309  2.557689
6           9426  mp-1220565  1.129870
7       E   9427    mp-38816  0.633848
8           9428    mp-10867  0.267304
9       E   9429     mp-4195  0.241615
10          9442  mp-1273854  4.361690
11          9443  mp-1224805  0.423934
12          9564   mp-676762  1.766004
13      E   9573  mp-1102240  1.459751
14          9574  mp-1113559  0.522127
15         10035    mp-19376  1.720263
16         10036    mp-10091  1.273993
17      E  10045     mp-6509  1.857082
18         10046   mp-975522  0.191778
19      E  10047  mp-1225893  0.149640
20         10089   mp-862832  0.187392

In [12]:
mp20_results

     status   idx material_id      time
0         E     0    mp-10009  0.179174
1         E     1  mp-1218989  0.137652
2         x     2  mp-1225695  1.188268
3               3  mp-1220884  1.707755
4               4  mp-1224266  2.922140
...     ...   ...         ...       ...
9041         9041    mp-21084  3.431612
9042         9042   mp-571486  4.601307
9043         9043    mp-14410  6.725072
9044         9044  mp-1079192  1.939557
9045         9045    mp-13501  0.563626

[9046 rows x 4 columns]